package com.sanalberto.clientes;
// Generated 26 ene. 2021 11:10:12 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Artist generated by hbm2java
 */
@Entity
@Table(name = "artist", catalog = "chinook")
public class Artist implements java.io.Serializable {

	private Integer artistId;
	private String name;
	private Set<Album> albums = new HashSet<Album>(0);

	public Artist() {
	}

	public Artist(String name, Set<Album> albums) {
		this.name = name;
		this.albums = albums;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ArtistId", unique = true, nullable = false)
	public Integer getArtistId() {
		return this.artistId;
	}

	public void setArtistId(Integer artistId) {
		this.artistId = artistId;
	}

	@Column(name = "Name", length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "artist")
	public Set<Album> getAlbums() {
		return this.albums;
	}

	public void setAlbums(Set<Album> albums) {
		this.albums = albums;
	}

}
