package com.sanalberto.clientes;
// Generated 26 ene. 2021 11:10:12 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mediatype generated by hbm2java
 */
@Entity
@Table(name = "mediatype", catalog = "chinook")
public class Mediatype implements java.io.Serializable {

	private Integer mediaTypeId;
	private String name;
	private Set<Track> tracks = new HashSet<Track>(0);

	public Mediatype() {
	}

	public Mediatype(String name, Set<Track> tracks) {
		this.name = name;
		this.tracks = tracks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MediaTypeId", unique = true, nullable = false)
	public Integer getMediaTypeId() {
		return this.mediaTypeId;
	}

	public void setMediaTypeId(Integer mediaTypeId) {
		this.mediaTypeId = mediaTypeId;
	}

	@Column(name = "Name", length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mediatype")
	public Set<Track> getTracks() {
		return this.tracks;
	}

	public void setTracks(Set<Track> tracks) {
		this.tracks = tracks;
	}

}
