package com.sanalberto.clientes;
// Generated 26 ene. 2021 11:10:12 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Playlist generated by hbm2java
 */
@Entity
@Table(name = "playlist", catalog = "chinook")
public class Playlist implements java.io.Serializable {

	private Integer playlistId;
	private String name;
	private Set<Track> tracks = new HashSet<Track>(0);

	public Playlist() {
	}

	public Playlist(String name, Set<Track> tracks) {
		this.name = name;
		this.tracks = tracks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PlaylistId", unique = true, nullable = false)
	public Integer getPlaylistId() {
		return this.playlistId;
	}

	public void setPlaylistId(Integer playlistId) {
		this.playlistId = playlistId;
	}

	@Column(name = "Name", length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "playlisttrack", catalog = "chinook", joinColumns = {
			@JoinColumn(name = "PlaylistId", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "TrackId", nullable = false, updatable = false) })
	public Set<Track> getTracks() {
		return this.tracks;
	}

	public void setTracks(Set<Track> tracks) {
		this.tracks = tracks;
	}
	

}
